### ISSUE TITLE
TypeError: AdminJSExpress.buildAuthenticatedRouter is not a function

### ISSUE THREAD

**Issue by dickorydock** [SoftwareBrothers/adminjs-expressjs#111]
I've tried implementing the example of an authenticated router provided [here](https://docs.adminjs.co/installation/plugins/express) but I am running into an error message. 

I have changed to use my DB_URI and I am able to access DB_URI both locally and remotely on my fly.io app, but in both cases I run into this error:
```

  const adminRouter = AdminJSExpress.buildAuthenticatedRouter(
                                     ^

TypeError: AdminJSExpress.buildAuthenticatedRouter is not a function
    at start (file:///home/localaccount/Documents/flyapps/veyerollfly/serveradmin.js:40:38)
    at file:///home/localaccount/Documents/flyapps/veyerollfly/serveradmin.js:67:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

```

Here is the code I am running, based off that adminjsexpress example:
```

import AdminJS from 'adminjs'
import * as AdminJSExpress from '@adminjs/express'
import express from 'express'
import Connect from 'connect-pg-simple'
import session from 'express-session'
// import  from 'express-session'
import * as dotenv from 'dotenv' // see https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import
dotenv.config()

const PORT = 3000

const DEFAULT_ADMIN = {
  email: 'admin@example.com',
  password: 'password',
}

const authenticate = async (email, password) => {
  if (email === DEFAULT_ADMIN.email && password === DEFAULT_ADMIN.password) {
    return Promise.resolve(DEFAULT_ADMIN)
  }
  return null
}
console.log("hi");
console.log(process.env.DB_URI);
const start = async () => {
  const app = express()

  const admin = new AdminJS({})

  const ConnectSession = Connect(session)
  const sessionStore = new ConnectSession({
    conObject: {
      connectionString: process.env.DB_URI,
      ssl: process.env.NODE_ENV === 'production',
    },
    tableName: 'session',
    createTableIfMissing: true,
  })

  const adminRouter = AdminJSExpress.buildAuthenticatedRouter(
    admin,
    {
      authenticate,
      cookieName: 'adminjs',
      cookiePassword: 'sessionsecret',
    },
    null,
    {
      store: sessionStore,
      resave: true,
      saveUninitialized: true,
      secret: 'sessionsecret',
      cookie: {
        httpOnly: process.env.NODE_ENV === 'production',
        secure: process.env.NODE_ENV === 'production',
      },
      name: 'adminjs',
    }
  )
  app.use(admin.options.rootPath, adminRouter)

  app.listen(PORT, () => {
    console.log(`AdminJS started on http://localhost:${PORT}${admin.options.rootPath}`)
  })
}

start()
```

**Comment by davyjones3392** [comment]
I am having the exactly same issue. Any help?

**Comment by dziraf** [comment]
Change:
```
import * as AdminJSExpress from '@adminjs/express'
```
to
```
import AdminJSExpress from '@adminjs/express'
```

This was updated only in one snippet of the docs, I'll fix it later.

**Comment by dfioravanti** [comment]
> Change:
> 
> ```
> import * as AdminJSExpress from '@adminjs/express'
> ```
> 
> to
> 
> ```
> import AdminJSExpress from '@adminjs/express'
> ```
> 
> This was updated only in one snippet of the docs, I'll fix it later.

Just as a FYI, you should update the import in https://docs.adminjs.co/installation/plugins/express too. It looks me a while to track down why the base example was not compiling
